remote_theme: kitian616/jekyll-TeXt-theme
plugins:
  - jekyll-remote-theme

title: Galt's Gulch Code
description: Critical evaluations...
skin: orange   # Try "ocean" for blue or "default" for bright mix